config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products

  root :to => "products#index"

  get     "login"    => "session#new"
  post    "login"    => "session#create"
  delete  "logout"   => "session#destroy"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :enrollments
  has_many :category, through: :enrollments
  validates :name, length: { minimum: 3 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :images)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
    <h1>Products</h1>
  
    <table>
    <% @products.each do |product| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
            <td>
                <%= image_tag(product.images, :class => 'list_image') %>
            </td>
  
            <td class="list_description">
                <dl>
                    <dt><%= product.name %></dt>
                    <dd><%= truncate(strip_tags(product.description),
                            :length => 80) %></dd>
                    <dd></dd>
                </dl>
            </td>
  
            <td class="list_actions">
                <%= link_to 'Show', product %><br/>
                <%= link_to 'Edit', edit_product_path(product) %><br/>
                <%= link_to 'Destroy', product, 
                    data: { confirm: 'Are you sure?' },
                    :method => :delete %>
            </td>
        </tr>
    <% end %>
    </table>
</div>
 
<br />
 
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="product_list">
    <h1>Products <%=@product.id%> details</h1>
  
    <table>
        <tr class="list_line_even" >  
            <td>
                <%= image_tag(@product.images, :class => 'list_image') %>
            </td>
  
            <td class="list_description">
                <dl>
                    <dt><%= @product.name %></dt>
                    <dd><%= truncate(strip_tags(@product.description),
                            :length => 80) %></dd>
                </dl>
            </td>
  
            <td class="list_actions">
                <%= link_to 'Show', @product %><br/>
                <%= link_to 'Edit', edit_product_path(@product) %><br/>
                <%= link_to 'Destroy', @product, 
                    data: { confirm: 'Are you sure?' },
                    :method => :delete %>
            </td>
        </tr>
    </table>
</div>
 
<br />
 
<%= link_to 'New product', new_product_path %>